language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - pip install -r tests/requirements.txt
  - pip install argparse
  - pip install python-coveralls
script:
  - nosetests -v --with-coverage --cover-package=salve
after_success:
  - coveralls
